<style>
.ec-global-loader{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(7,7,7,.48);backdrop-filter:blur(5px);opacity:0;visibility:hidden;transition:.18s ease}.ec-global-loader.is-visible{opacity:1;visibility:visible}.ec-loader-card{min-width:190px;padding:24px 26px;background:#171717;color:#fff;text-align:center;box-shadow:0 22px 65px rgba(0,0,0,.28)}.ec-loader-ring{width:44px;height:44px;margin:0 auto 13px;border:3px solid rgba(255,255,255,.18);border-top-color:#d71920;border-radius:50%;animation:ecLoaderSpin .75s linear infinite}.ec-loader-title{font-family:'Oswald',sans-serif;font-size:14px;text-transform:uppercase}.ec-btn-spinner{width:15px;height:15px;display:inline-block;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;animation:ecLoaderSpin .65s linear infinite}.ec-toast-stack{position:fixed;right:18px;bottom:20px;z-index:100000;width:min(360px,calc(100vw - 28px));display:grid;gap:9px;pointer-events:none}.ec-toast{display:grid;grid-template-columns:30px 1fr auto;gap:10px;align-items:center;padding:12px 13px;border:1px solid #e3e3e3;background:#fff;color:#191919;box-shadow:0 15px 38px rgba(0,0,0,.13);pointer-events:auto;font-size:12px}.ec-toast-icon{width:30px;height:30px;display:flex;align-items:center;justify-content:center;background:#f4f4f4}.ec-toast-success .ec-toast-icon{color:#16885a;background:#edf9f3}.ec-toast-error .ec-toast-icon{color:#c42e33;background:#fff0f0}.ec-toast-warning .ec-toast-icon{color:#936b16;background:#fff8e9}.ec-toast-close{border:0;background:transparent;color:#aaa}@keyframes ecLoaderSpin{to{transform:rotate(360deg)}}
</style>

<div class="ec-global-loader" id="ecGlobalLoader" aria-hidden="true"><div class="ec-loader-card"><div class="ec-loader-ring"></div><div class="ec-loader-title" id="ecGlobalLoaderText">Loading</div></div></div>
<div class="ec-toast-stack" id="ecToastStack"></div>

<script>
(function(){
    let loaderDepth=0;
    function showLoader(text){loaderDepth++;const loader=document.getElementById('ecGlobalLoader'),label=document.getElementById('ecGlobalLoaderText');if(label)label.textContent=text||'Loading';if(loader){loader.classList.add('is-visible');loader.setAttribute('aria-hidden','false')}}
    function hideLoader(force){loaderDepth=force?0:Math.max(0,loaderDepth-1);if(loaderDepth>0)return;const loader=document.getElementById('ecGlobalLoader');if(loader){loader.classList.remove('is-visible');loader.setAttribute('aria-hidden','true')}}
    function buttonLoading(button,loading,label){if(!button)return;if(loading){if(!button.dataset.ecOriginalHtml)button.dataset.ecOriginalHtml=button.innerHTML;button.disabled=true;button.innerHTML='<span class="ec-btn-spinner"></span><span>'+(label||'Processing')+'</span>'}else{button.disabled=false;if(button.dataset.ecOriginalHtml){button.innerHTML=button.dataset.ecOriginalHtml;delete button.dataset.ecOriginalHtml}}}
    function toast(message,type){if(!message)return;type=type||'success';const stack=document.getElementById('ecToastStack');if(!stack)return;const icons={success:'bi-check-circle',error:'bi-exclamation-circle',warning:'bi-exclamation-triangle'};const el=document.createElement('div');el.className='ec-toast ec-toast-'+type;el.innerHTML='<span class="ec-toast-icon"><i class="bi '+(icons[type]||icons.success)+'"></i></span><span></span><button type="button" class="ec-toast-close" aria-label="Close"><i class="bi bi-x-lg"></i></button>';el.children[1].textContent=message;el.querySelector('.ec-toast-close').addEventListener('click',()=>el.remove());stack.appendChild(el);setTimeout(()=>{if(el.isConnected)el.remove()},4200)}
    async function json(response){const data=await response.json().catch(()=>({}));if(!response.ok&&!data.message)data.message='Request failed. Please try again.';return data}
    window.EncoreShopUI={showLoader,hideLoader,buttonLoading,toast,json};
})();
</script>
